### ISSUE TITLE
`ReferenceError: document is not defined

### ISSUE THREAD

**Issue by smarques** [chrisguttandin/timing-provider#145]
Hi, I am trying to run my own timing provider for a local network application, but I can not build the project, here is the error msg:

`node_modules/timing-object/build/es5/bundle.js:501`

`var timingObjectConstructor = createTimingObjectConstructor(createCalculateTimeoutDelay(createCalculateDelta(createCalculatePositiveRealSolution(calculateRealSolutions))), createIllegalValueError, createInvalidStateError, createEventTargetConstructor(document), filterTimingStateVectorUpdate, performance, setTimeout);`

`ReferenceError: document is not defined
    at node_modules/timing-object/build/es5/bundle.js:501:256
    at node_modules/timing-object/build/es5/bundle.js:2:68
    at Object.<anonymous> (/node_modules/timing-object/build/es5/bundle.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)`

I suspect this has to do with tsconfig but I am no expert, 
any hint would be appreciated.
TIA

**Comment by chrisguttandin** [comment]
Hi @smarques,

the error looks to me as if you are running the code outside of the browser. Is that possible? The package is meant to run in the browser and therefore expects the global document variable to be defined.

**Comment by smarques** [comment]
Thank you for your reply... so now I am confused.. I thought this was a timing provider 'server' like the one used here https://webtiming.github.io/timingsrc/doc/shared_motion.html and provided by MCorp. 
Is this correct? Are there any use examples?

Thanks and sorry for the newbieness :)

**Comment by chrisguttandin** [comment]
Yes and no. :-) This is not the server itself. It's the code which communicates with the server and establishes the peer2peer connections. Therefore `timing-provider` is meant to run in the browser similar to the library hosted at www.mcorp.no/lib/mcorp-2.0.js.

The server used by `timing-provider` is running on suenc.io. It requires an API key to be used. Please send me an email if you need one.

**Comment by smarques** [comment]
Ah I see now, thank you, so there is no open source implementation of the server component? :<

**Comment by chrisguttandin** [comment]
No there is no implementation that I'm aware of. Do you want to use this in a local network without any internet connection?

**Comment by smarques** [comment]
Yes the idea was to create a local network of synchronised web audio generators, I expected there would be an open implementation so I could create a local timing server :< I hope somebody releases one sooner or later :)

**Comment by chrisguttandin** [comment]
I'm not aware of any implementation that would run locally. I created the hosted signaling server because I thought it would make things easier. But that does of course fall short if there is no internet connection.

I'm closing this issue now since the originally reported error is expected. Please feel free to create a new issue for supporting locally running servers. That would allow us to see if there is a broader interest in that feature.

**Comment by smarques** [comment]
Yes, thank you for your replies.
