### ISSUE TITLE
Example of how to use it

### ISSUE THREAD

**Issue by donlucacorleone** [chrisguttandin/timing-provider#15]
Hi Chris,
can you show an example of how to use it?

I don't know if it's intended to be run in client-side (browser) or server-side (NodeJS).

An actual example or a brief instructions will be very helpful.

Keep up the good work.
Luca

**Comment by donlucacorleone** [comment]
Hi Chris, thanks for your reply.
Can you help me understand better the general workflow of this TimingProvider?

Reading your code I can assume it's something like that:
Clients "connect" (I don't know the precise term for WebRTC) to each other.
The server is needed only for make them aware of each other.
Every time an `update` event is fired (e.g. "play" command from ClientA), a message with `vector` and `timestamp` is sent from ClientA to other clients.
Each client listens to `update` event and sets its internal `vector` to the new one arrived together with the `update` message. How do you use `timestamp`s to correctly align `position`s?

Am i missing something?

Thank you again for your kind help.

**Comment by mrchantey** [comment]
in case this helps:

```html
<body>
    <video src="video.mp4"></video>
    <button id="play-button">Play</button>
    <button id="pause-button">Pause</button>
</body>
```

```ts
/*
simple implementation of chris guttandin's timing object etc.

dependencies:
https://www.npmjs.com/package/timing-object
https://www.npmjs.com/package/timingsrc

https://www.npmjs.com/package/timing-provider
https://www.npmjs.com/package/timing-provider-server

*/

import { TimingObject } from 'timing-object';
import { TimingProvider } from 'timing-provider';
import { setTimingsrc } from 'timingsrc';

const socketURL = `ws://localhost:2276`

const timingProvider = new TimingProvider(socketURL);
const mediaElement = document.getElementsByTagName('video')[0];

let timingObject

timingProvider.onreadystatechange = e => {
    const provider = e.target as any
    if (provider.readyState === "open") {
        timingObject = new TimingObject(timingProvider);
        const deleteTimingsrc = setTimingsrc(mediaElement, timingObject);
    }
}

document.getElementById('play-button')
    .addEventListener('click', () => {
        timingObject.update({ velocity: 1 })
    })
document.getElementById('pause-button')
    .addEventListener('click', () => {
        timingObject.update({ velocity: 0 })
    })

```

**Comment by chrisguttandin** [comment]
Thanks for the example @mrchantey. I meanwhile also created some examples which might be helpful.

https://chrisguttandin.github.io/video-synchronization-demo/
https://chrisguttandin.github.io/web-audio-metronome-demo/
https://chrisguttandin.github.io/web-timing-demo/
