### ISSUE TITLE
Support local network timing provider

### ISSUE THREAD

**Issue by smarques** [chrisguttandin/timing-provider#153]
It would be an interesting improvement to be able to set up a timing provider on a local network.

Use cases:
laptop orchestras
art installations
synced media rooms

Thank you for the great work

**Comment by chrisguttandin** [comment]
I think this would be a nice feature.

If someone wants to help with this please reach out. I'm happy to accept contributions.

In case you come across this and want to show that you would love to see this being implemented, please add a 👍response to the message above.

**Comment by chrisguttandin** [comment]
Today I published the [`timing-provider-server`](https://github.com/chrisguttandin/timing-provider-server) command line tool. It can be used to create a very simple local server.

**Comment by smarques** [comment]
GREAT!!!!
